document.getElementById('triangle-calc').addEventListener('click',function(){
    areaCalculation('triangle-value-b','triangel-value-h','triangle');
    console.log('clicked')
});
document.getElementById('rectangle-calc').addEventListener('click',function(){
    areaCalculation('rectangle-value-w','rectangle-value-l','rectangle');
    console.log('clicked')
});
document.getElementById('parallelogram-calc').addEventListener('click',function(){
    areaCalculation('parallelogram-value-b','parallelogram-value-h','parallelogram')
    console.log('clicked')
});
document.getElementById('rhombus-calc').addEventListener('click',function(){
    areaCalculation('rhombus-value-b','rhombus-value-h','parallelogram')
    console.log('clicked')
});
document.getElementById('pentagon-calc').addEventListener('click',function(){
    areaCalculation('pentagon-value-d1','pentagon-value-d2','pentagon')
    console.log('clicked')
});
document.getElementById('ellipse-calc').addEventListener('click',function(){
    areaCalculation('ellipse-value-a','ellipse-value-b','ellipse')
    console.log('clicked')
});